---
- name: Include OS-family specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Define acme_packages.
  ansible.builtin.set_fact:
    acme_packages: "{{ __acme_packages | list }}"
  when: acme_packages is not defined

- name: Define acme_webroot_group.
  ansible.builtin.set_fact:
    acme_webroot_group: "{{ __acme_webroot_group }}"
  when: acme_webroot_group is not defined

- name: Include install tasks for RedHat.
  ansible.builtin.include_tasks: install-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Include install tasks for Debian.
  ansible.builtin.include_tasks: install-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Include install tasks for FreeBSD.
  ansible.builtin.include_tasks: install-FreeBSD.yml
  when: ansible_os_family == 'FreeBSD'

- name: Add dedicated user
  ansible.builtin.user:
    name: "{{ acme_username }}"
    shell: /usr/sbin/nologin
    comment: For acme.sh
    system: true
    home: "{{ acme_home_directory }}"

- name: Create PKI directory for acme
  ansible.builtin.file:
    path: "{{ acme_certificate_directory }}"
    owner: "{{ acme_username }}"
    group: "{{ acme_username }}"
    mode: "0700"
    state: directory

- name: Download acme.sh
  ansible.builtin.get_url:
    url: https://get.acme.sh
    dest: /tmp/get.acme.sh
    owner: "{{ acme_username }}"
    group: "{{ acme_username }}"
    mode: "0755"

- name: Install acme.sh
  ansible.builtin.command: /tmp/get.acme.sh
  args:
    chdir: "{{ acme_home_directory }}"
    creates: "{{ acme_home_directory }}/.acme.sh/acme.sh"
  environment:
    HOME: "{{ acme_home_directory }}"

- name: Setup SSL Cert using Webroot
  when: acme_method == 'webroot' and acme_certificates is defined
  block:
    - name: Issue certificate standalone for bootstrap webroot
      ansible.builtin.command: >
        {{ acme_home_directory }}/.acme.sh/acme.sh --issue
        {% for d in item.d %}-d {{ d }} {% endfor %}
        --home {{ acme_home_directory }}/.acme.sh
        --standalone
        --certpath {{ acme_certificate_directory }}/{{ item.d[0] }}-cert.pem
        --keypath {{ acme_certificate_directory }}/{{ item.d[0] }}-key.pem
        --fullchainpath {{ acme_certificate_directory }}/{{ item.d[0] }}-fullchain.pem
      args:
        creates: "{{ acme_certificate_directory }}/{{ item.d[0] }}-cert.pem"
      loop: "{{ acme_certificates }}"

    - name: Create .well-known/acme-challenge
      ansible.builtin.file:
        state: directory
        path: "{{ acme_webroot_directory }}/.well-known/acme-challenge"
        owner: "{{ acme_username }}"
        group: "{{ acme_webroot_group }}"
        mode: "0755"

    - name: Switch to webroot for certificate
      ansible.builtin.lineinfile:
        dest: "{{ acme_home_directory }}/.acme.sh/{{ item[0].d[0] }}/{{ item[0].d[0] }}.conf"
        regexp: "^{{ item[1].k }}='.*'$"
        line: "{{ item[1].k }}='{{ item[1].v }}'"
      loop_control:
        label: "{{ item[0].d[0] }} - {{ item[1].k }}={{ item[1].v }}"
      with_nested:
        - "{{ acme_certificates }}"
        - - {k: "Le_Webroot", v: "{{ acme_webroot_directory }}"}

- name: Setup SSL Cert using Route 53
  when: acme_method == 'route53' and acme_certificates is defined
  block:
    - name: Configure AWS API key
      ansible.builtin.lineinfile:
        dest: "{{ acme_home_directory }}/.acme.sh/account.conf"
        regexp: "^{{ item.k }}='.*'$"
        line: "{{ item.k }}='{{ item.v }}'"
      loop_control:
        # Don't expose the key in the log
        label: "{{ item.k }}"
      loop:
        - {k: "AWS_ACCESS_KEY_ID", v: "{{ acme_aws_access_key_id }}"}
        - {k: "AWS_SECRET_ACCESS_KEY", v: "{{ acme_aws_secret_access_key }}"}

    - name: Issue certificate using Route53 (This will take 40s due to DNS)
      ansible.builtin.command: >
        {{ acme_home_directory }}/.acme.sh/acme.sh --issue
        {% for d in item.d %}-d {{ d }} {% endfor %}
        --home {{ acme_home_directory }}/.acme.sh
        --dns dns_aws
        --dnssleep 40
        --certpath {{ acme_certificate_directory }}/{{ item.d[0] }}-cert.pem
        --keypath {{ acme_certificate_directory }}/{{ item.d[0] }}-key.pem
        --fullchainpath {{ acme_certificate_directory }}/{{ item.d[0] }}-fullchain.pem
      args:
        creates: "{{ acme_certificate_directory }}/{{ item.d[0] }}-cert.pem"
      loop: "{{ acme_certificates }}"

    - name: Change DNS Sleep to 120 seconds
      ansible.builtin.lineinfile:
        dest: "{{ acme_home_directory }}/.acme.sh/{{ item[0].d[0] }}/{{ item[0].d[0] }}.conf"
        regexp: "^{{ item[1].k }}='.*'$"
        line: "{{ item[1].k }}='{{ item[1].v }}'"
      loop_control:
        label: "{{ item[0].d[0] }} - {{ item[1].k }}={{ item[1].v }}"
      with_nested:
        - "{{ acme_certificates }}"
        - - {k: "Le_DNSSleep", v: "120"}

- name: Give acme ownership of certificate directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ acme_username }}"
    group: "{{ acme_username }}"
    recurse: true
  loop:
    - "{{ acme_home_directory }}/.acme.sh"
    - "{{ acme_certificate_directory }}"

- name: Setup cron for managing renewal of certs
  ansible.builtin.cron:
    name: "Cron for acme.sh"
    minute: "0"
    hour: "0"
    user: "{{ acme_username }}"
    job: "{{ acme_home_directory }}/.acme.sh/acme.sh --cron --home {{ acme_home_directory }}/.acme.sh > /dev/null"
